django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls import patterns, include
from django.views.generic.simple import direct_to_template
from django.contrib import admin
from grants.admin import advanced_admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import grants, fund

urlpatterns = patterns('',

## ADMIN ##

    (r'^admin/', include(admin.site.urls)),
    (r'^admin-advanced/', include(advanced_admin.urls)),

## LANDING ##    

    (r'^$', 'django.views.generic.simple.direct_to_template', {'template': 'home.html'}),
    
## GRANTS - ORGANIZATION VIEWS ##
    
    #login, logout, registration
    (r'^org/login/$', 'grants.views.OrgLogin'),
    (r'^org/register/$', 'grants.views.OrgRegister'),
    (r'^org/nr', direct_to_template, {'template': 'grants/not_grantee.html'}),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/org'}),
    
    #reset password
    (r'^org/reset$', 'django.contrib.auth.views.password_reset', {'template_name':'grants/reset.html', 'from_email':'webmaster@socialjusticefund.org', 'email_template_name':'grants/password_reset_email.html'}),
    (r'^org/reset-sent', 'django.contrib.auth.views.password_reset_done', {'template_name':'grants/password_reset_done.html'}),
    (r'^org/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name':'grants/password_reset_confirm.html'}),
    (r'^org/reset-complete', 'django.contrib.auth.views.password_reset_complete', {'template_name':'grants/password_reset_complete.html'}),
     
     #main pages
    (r'^org/$','grants.views.OrgHome'),
    (r'^org/support', 'grants.views.OrgSupport'),
    
    #application
    (r'^apply/(?P<cycle_id>\d+)/$','grants.views.Apply'),
    (r'^apply/(?P<cycle_id>\d+)/autosave/$','grants.views.AutoSaveApp'),
    (r'^apply/(?P<cycle_id>\d+)/DELETE$', 'grants.views.DiscardDraft'),
    (r'^org/submitted.html', direct_to_template, {'template': 'grants/submitted.html'}),
    
    #cron
    (r'^mail/drafts/', 'grants.views.DraftWarning'),

## GRANTS - APPLICATION VIEWS ##
    (r'^grants/view/(?P<app_id>\d+)/$', 'grants.views.view_app'),
    (r'^grants/download/(?P<filename>.*)$', 'grants.views.download_handler'),
    
## GRANTS - REPORTING ##
  
    (r'^grants/grant_application/$', 'grants.search.search'),
    (r'^grants/grant_application/search', 'grants.search.search'),
    (r'^grants/grant_application/results', 'grants.search.results'),
    (r'^grants/grant_application/(?P<grant_application_id>\d+)/$', 'grants.search.show'),

    # These endpoints return the serialized json form of these models
    (r'^grants/api/grant_application/results',
            'grants.search.api_grant_applications'),

    (r'^grants/api/grant_application/(?P<grant_application_id>\d+)/$',
        'grants.search.api_show_grant_application'),

    (r'^grants/api/grantee/(?P<grantee_id>\d+)/$',
        'grants.search.api_show_grantee'),

    (r'^grants/api/grant_cycle/(?P<grant_cycle_id>\d+)/$',
        'grants.search.api_show_grant_cycle'),

    # Endpoint for csv
    (r'^grants/csv/grant_application/results',
        'grants.search.csv_grant_applications'),

    (r'^grants/csv/grant_application/(?P<grant_application_id>\d+)/$',
        'grants.search.csv_show_grant_application'),

    #Reporting URLs should start with /grants

## SCORING ##
    
    #Scoring URLs should start with /scoring
    
## FUNDRAISING ##
    
    #login, logout, registration
    (r'^fund/login/$', 'fund.views.FundLogin'),
    (r'^fund/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/fund'}),
    (r'^fund/register/$', 'fund.views.Register'),
    (r'^fund/registered/$', 'fund.views.Registered'),
    
    #reset password
    (r'^fund/reset$', 'django.contrib.auth.views.password_reset', {'template_name':'fund/reset.html', 'from_email':'webmaster@socialjusticefund.org', 'email_template_name':'fund/password_reset_email.html', 'subject_template_name':'registration/password_reset_subject.txt'}),
    (r'^fund/reset-sent', 'django.contrib.auth.views.password_reset_done', {'template_name':'fund/password_reset_done.html'}),
    (r'^fund/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name':'fund/password_reset_confirm.html'}),
    (r'^fund/reset-complete', 'django.contrib.auth.views.password_reset_complete', {'template_name':'fund/password_reset_complete.html'}),
    
    #manage memberships
    (r'^fund/projects', 'fund.views.Projects'),
    (r'^fund/set-current/(?P<ship_id>\d+)/', 'fund.views.SetCurrent'),
    
    #main pages
    (r'^fund/$', 'fund.views.Home'),
    (r'^fund/gp', 'fund.views.News'),
    (r'^fund/apps', 'fund.views.ScoringList'),
    
    #forms - contacts
    (r'^fund/add$', 'fund.views.AddDonor'),
    (r'^fund/addmult', 'fund.views.AddMult'),
    (r'^fund/(?P<donor_id>\d+)/edit','fund.views.EditDonor'),
    (r'^fund/(?P<donor_id>\d+)/delete', 'fund.views.DeleteDonor'),
    
    #forms - steps
    (r'^fund/(?P<donor_id>\d+)/step$','fund.views.AddStep'),
    (r'^fund/stepmult$','fund.views.AddMultStep'),
    (r'^fund/(?P<donor_id>\d+)/(?P<step_id>\d+)/$','fund.views.EditStep'),
    (r'^fund/(?P<donor_id>\d+)/(?P<step_id>\d+)/done','fund.views.DoneStep'),
    
    #error/help pages
    (r'^fund/not-member', 'fund.views.NotMember'),
    (r'^fund/pending$', 'fund.views.NotApproved'),
    (r'^fund/contact', direct_to_template, {'template': 'fund/contact_us.html'}),
    (r'^fund/support', 'fund.views.Support'),
    (r'^fund/blocked$', 'fund.views.Blocked'),
    
    #admin
    (r'^fund/stats/$', 'fund.views.Stats'),
    (r'^fund/stats/(?P<gp_id>\d+)/$', 'fund.views.StatsSingle'),
    
    #cron
    (r'^mail/overdue-step', 'fund.views.EmailOverdue'),
    (r'^mail/new-accounts', 'fund.views.NewAccounts'),
    (r'^mail/gifts', 'fund.views.GiftNotify'),
    
## DEVEL ##
  
    (r'^fund/populate','fund.views.PopulateDB'),
    (r'test/$', 'grants.views.TestView'),
    (r'update-db', 'fund.views.UpdateDB'),
  )

  #for devel since using appengine
urlpatterns += staticfiles_urlpatterns()

fund/models.py
from django import forms
from django.db import models
from django.forms import ModelForm
import datetime
from grants.models import GrantCycle
from django.utils import timezone

class GivingProject(models.Model):
  title = models.CharField(max_length=255)

  #fundraising
  fundraising_deadline = models.DateField(help_text='Members will stop receiving reminder emails at this date.')
  fund_goal = models.PositiveIntegerField(default=0)
  pre_approved = models.TextField(null=True, blank=True, help_text='List of member emails, separated by commas.  Anyone who registers using an email on this list will have their account automatically approved.  Emails are removed from the list once they have registered.  IMPORTANT: Any syntax error can make this feature stop working; in that case memberships will default to requiring manual approval by an administrator.') #remove null from all char
  
  calendar = models.CharField(max_length=255, null=True, blank=True, help_text= 'Calendar ID of a google calendar (not the whole embed text)')
  r1title = models.CharField(verbose_name='Resource title', max_length=255, null=True, blank=True)
  r1link= models.URLField(verbose_name='Resource link', null=True, blank=True)
  r2title = models.CharField(verbose_name='Resource title', max_length=255, null=True, blank=True)
  r2link= models.URLField(verbose_name='Resource link', null=True, blank=True)
  r3title = models.CharField(verbose_name='Resource title', max_length=255, null=True, blank=True)
  r3link= models.URLField(verbose_name='Resource link', null=True, blank=True)
  r4title = models.CharField(verbose_name='Resource title', max_length=255, null=True, blank=True)
  r4link= models.URLField(verbose_name='Resource link', null=True, blank=True)
  r5title = models.CharField(verbose_name='Resource title', max_length=255, null=True, blank=True)
  r5link= models.URLField(verbose_name='Resource link', null=True, blank=True)
  r6title = models.CharField(verbose_name='Resource title', max_length=255, null=True, blank=True)
  r6link= models.URLField(verbose_name='Resource link', null=True, blank=True)
  r7title = models.CharField(verbose_name='Resource title', max_length=255, null=True, blank=True)
  r7link= models.URLField(verbose_name='Resource link', null=True, blank=True)
  r8title = models.CharField(verbose_name='Resource title', max_length=255, null=True, blank=True)
  r8link= models.URLField(verbose_name='Resource link', null=True, blank=True)
  r9title = models.CharField(verbose_name='Resource title', max_length=255, null=True, blank=True)
  r9link= models.URLField(verbose_name='Resource link', null=True, blank=True)
  r10title = models.CharField(verbose_name='Resource title', max_length=255, null=True, blank=True)
  r10link= models.URLField(verbose_name='Resource link', null=True, blank=True)

  #grant
  grant_cycle = models.ForeignKey(GrantCycle, null=True, blank=True)

  def __unicode__(self):
    return self.title+' '+str(self.fundraising_deadline.year)

  def talked(self):
    return Donor.objects.filter(membership__giving_project=self, talked=True).count()

  def asked(self):
    return Donor.objects.filter(membership__giving_project=self, asked=True).count()

  def contacts(self):
    return Donor.objects.filter(membership__giving_project=self).count()

  def pledged(self):
    donors = Donor.objects.filter(membership__giving_project=self)
    pledged = 0
    for donor in donors:
      if donor.pledged:
        pledged = pledged + donor.pledged
    return pledged

  def bar_width(self):
    if self.fund_goal>0:
      pl = self.pledged()
      if pl>self.fund_goal:
        return 100
      else:
        return 100*pl/self.fund_goal
    else:
      return 0

  def gifted(self):
    donors = Donor.objects.filter(membership__giving_project=self, gifted__gt=0)
    gifted = 0
    for donor in donors:
      gifted = gifted + donor.gifted()
    return gifted

  def estimated(self):
    estimated = 0
    donors = Donor.objects.filter(membership__giving_project=self)
    for donor in donors:
      estimated = estimated + donor.amount*donor.likelihood/100
    return estimated
    
class Member(models.Model):
  email = models.CharField(max_length=255)
  first_name = models.CharField(max_length=100)
  last_name = models.CharField(max_length=100)
  
  giving_project = models.ManyToManyField(GivingProject, through='Membership')
  current = models.IntegerField(default=0)
  
  def __unicode__(self):
    return self.first_name+' '+self.last_name
  
class Membership(models.Model): #relationship b/n member and gp
  giving_project = models.ForeignKey(GivingProject)
  member = models.ForeignKey(Member)
  approved = models.BooleanField(default=False)
  leader = models.BooleanField(default=False)
  
  emailed = models.DateField(default='2000-01-01', help_text='Last time this member was sent an overdue steps reminder')
  last_activity = models.DateField(default='2000-01-01', help_text='Last activity by this user on this membership.')
  
  notifications = models.TextField(default='', blank=True)
  
  def __unicode__(self):
    return str(self.member)+', '+str(self.giving_project)
    
  def has_overdue(self):
    donors = self.donor_set.all()
    overdue = 0
    day = datetime.timedelta(days=1)
    for donor in donors:
      if donor.has_overdue() and donor.has_overdue()>day: #1 day grace period to member to update
        overdue = overdue+1
    return overdue

  def talked(self):
    return self.donor_set.filter(talked=True).count()

  def asked(self):
    return self.donor_set.filter(asked=True).count()

  def bar_width(self):
    if self.donor_set.count()>0:
      return 100*self.asked()/self.donor_set.count()
    else:
      return 0
        
  def pledged(self):
    donors = self.donor_set.all()
    amt = 0
    for donor in donors:
      if donor.pledged:
        amt = amt + donor.pledged
    return amt
  
  def gifted(self):
    donors = self.donor_set.all()
    amt = 0
    for donor in donors:
      amt = amt + donor.gifted
    return amt

  def estimated(self):
    estimated = 0
    donors = self.donor_set.all()
    for donor in donors:
      estimated = estimated + donor.amount*donor.likelihood/100
    return estimated

class Donor(models.Model):
  membership = models.ForeignKey(Membership)
  
  firstname = models.CharField(max_length=100, verbose_name='*First name')
  lastname = models.CharField(max_length=100, null=True, blank=True, verbose_name='Last name')
  PRIVACY_CHOICES = (
    ('PR', 'Private - cannot be seen by staff'),
    ('SH', 'Shared'),
  )
  privacy = models.CharField(max_length=2, choices=PRIVACY_CHOICES, default='SH')
  amount = models.PositiveIntegerField(verbose_name='*Amount to ask ($)')
  likelihood = models.PositiveIntegerField(verbose_name='*Estimated likelihood (%)')
  talked = models.BooleanField(default=False)
  asked = models.BooleanField(default=False)
  pledged = models.PositiveIntegerField(blank=True, null=True)
  gifted = models.PositiveIntegerField(default=0)
  gift_notified = models.BooleanField(default=False)
  phone = models.CharField(max_length=15, null=True, blank=True)
  email = models.EmailField(null=True, blank=True)
  
  def __unicode__(self):
    return self.firstname+' '+self.lastname
  
  def get_next_step(self):
    step = Step.objects.filter(donor=self, complete=False)
    if step:
      return step[0]
    else:
      return None
  
  def get_next_date(self): #used to sort donors
    step = Step.objects.filter(donor=self, complete=False)
    
    if step: #next step - top
      return step[0].date
    elif self.pledged: # 'done' - all the way to bottom
      return timezone.now().date()+datetime.timedelta(weeks=100)
    else: #no step, not done - middle
      return timezone.now().date()+datetime.timedelta(weeks=70)
    
  def get_steps(self): #used in expanded view
    return Step.objects.filter(donor=self).filter(complete=True).order_by('date')
  
  def has_overdue(self):
    steps = Step.objects.filter(donor=self, complete=False)
    for step in steps:
      if step.date < timezone.now().date():
        return timezone.now().date()-step.date
    return False
  
def make_custom_datefield(f):
  """date selector implementation from http://strattonbrazil.blogspot.com/2011/03/using-jquery-uis-date-picker-on-all.html """
  formfield = f.formfield()
  if isinstance(f, models.DateField):
      formfield.widget.format = '%m/%d/%Y'
      formfield.widget.attrs.update({'class':'datePicker', 'readonly':'true'})
  return formfield
    
class DonorForm(ModelForm): #used to edit, creation uses custom form
  class Meta:
    model = Donor
    fields = ('firstname', 'lastname', 'amount', 'likelihood', 'phone', 'email', 'asked', 'pledged')

class Step(models.Model):  
  date = models.DateField(verbose_name='Date')
  description = models.CharField(max_length=255, verbose_name='Description')
  donor = models.ForeignKey(Donor)
  complete = models.BooleanField(default=False)

  def __unicode__(self):
    return self.date.strftime('%m/%d/%y')+' '+self.description
    
class StepForm(ModelForm):
  formfield_callback = make_custom_datefield #date input
  
  class Meta:
    model = Step
    exclude = ('donor', 'complete')
    
class NewsItem(models.Model):
  date = models.DateTimeField(auto_now=True)
  project = models.ForeignKey(GivingProject)
  short = models.CharField(max_length=255, help_text='News summary that shows in the news box.')
  long = models.TextField(null=True, blank=True, help_text='(Optional) Longer text to display on the news page.')
  title = models.CharField(max_length=255, null=True, blank=True, help_text='If including a long text, also include a title for the news page display.')

grants/forms.py
from django import forms
import models, datetime

class LoginForm(forms.Form):
	username = forms.EmailField()
	password = forms.CharField(widget=forms.PasswordInput())

class RegisterForm(forms.Form):
	email = forms.EmailField()
	password = forms.CharField(widget=forms.PasswordInput())
	organization = forms.CharField()

grants/templates/grants/grant_application/results.html
<!DOCTYPE>
<!-- Python vars: grant_applications -->
<html>
    <head>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="/static/css/style.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic+SC' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
        <div class="container">
            <div class="page-header">
                    <h1>results // <small>here are your grants.</small></h1>
            </div>
            <h3 class="pull-right"><a href="{{ csv }}">Click here to download results</a></h3>
                <table class="table table-hover">
                    <thead>
                            <tr>
                                <th scope="col" class="report_column"></th>
                                <th scope="col" class="report_column">Submission Date</th>
                                <th scope="col" class="report_column">Organization</th>
                                <th scope="col" class="report_column">City</th>
                                <th scope="col" class="report_column">State</th>
                                <th scope="col" class="report_column">Led by Color</th>
                            </tr>
                        </a>
                    </thead>
                    <tbody id="results">
                        {% for t in grant_applications %}
                        <tr>
                            <td scope="col" class="report_column"><a href="{{ t.pk }}">View Grant</a></td>
                            <td scope="col" class="report_column">{{ t.submission_time }}</td>
                            <td scope="col" class="report_column">{{ t.organization.name }}</td>
                            <td scope="col" class="report_column">{{ t.city }}</td>
                            <td scope="col" class="report_column">{{ t.state }}</td>
                            <td scope="col" class="report_column">{{ t.scoring_bonus_poc }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            <script>
                /*
                    for (var i = 0; i < arrayOfObjects.length; i++) {
                        var object = arrayOfObjects[i];

                        var row = $("<tr></tr>").appendTo($("#results"));

                        <!--Figure out correct attributes-->
                        $("<td><span>" + object.fields.submission_time + "</td></span>").appendTo(row);
                        $("<td><span>" + object.fields.organization + "</td></span>").appendTo(row);
                        $("<td><span>" + object.fields.project_budget + "</td></span>").appendTo(row);
                        $("<td><span>" + object.fields.city + "</td></span>").appendTo(row);
                        $("<td><span>" + object.fields.state + "</td></span>").appendTo(row);
                        $("<td><span>" + object.fields.scoring_bonus_poc + "</td></span>").appendTo(row);
                    }
                    */
            </script>
        </div>
    </body>
</html>

grants/templates/grants/grant_application/search.html
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="/static/css/style.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic+SC' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="/static/js/script.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
        <!--TODO: Add default 'if nothing selected' then ALL VALUES OK!-->
        <div class="container">
            <div class="page-header">
                <div class="row">
                    <h1 class="offset3 span5">search // <small>find your grants.</small></h1>
                </div>
            </div>
            <form id="search-form" action="results"> <!--TODO: Fill in action-->
                <div class="row">
                    <div class="offset3 span2">
                        <label class="input-title">Grantee/Organization</label>
                        <input type="text" name="grantee">
                    </div>
                </div>
                <div class="row input-separator">
                    <div class="span6 offset3"></div>
                </div>
                <div class="row">
                    <div class="span3"></div>
                    <div class="span3">
                        <label class="input-title">City</label>
                        <input id="city-textarea" type="text" name="city">
                    </div>
                    <div class="span3">
                        <label class="input-title">State</label>
                        <label id="state-label" class="checkbox">
                            <input type="checkbox" name="state" value="ID">Idaho</input><br />
                            <input type="checkbox" name="state" value="MT">Montana</input><br />
                            <input type="checkbox" name="state" value="OR">Oregon</input><br />
                            <input type="checkbox" name="state" value="WA">Washington</input><br />
                            <input type="checkbox" name="state" value="WY">Wyoming</input>
                        </label>
                    </div>
                    <div class="span3"></div>
                </div>
                
                <div class="row input-separator">
                    <div class="span6 offset3"></div>
                </div>

                <div class="row">
                    <div class="span3"></div>
                    <div class="span3">
                        <label class="input-title">Giving Project Type</label>
                        <label class="checkbox">
                            <input type="checkbox" name="giving_project" value="Civic Action Project">Civic Action Project<br />
                            <input type="checkbox" name="giving_project" value="Criminal Justice Giving Project">Criminal Justice Giving Project<br />
                            <input type="checkbox" name="giving_project" value=">Economic Justice Giving Project">Economic Justice Giving Project<br />
                            <input type="checkbox" name="giving_project" value="LGBTQ Giving Project">LGBTQ Giving Project<br />
                            <input type="checkbox" name="giving_project" value="Montana Giving Project">Montana Giving Project<br />
                            <input type="checkbox" name="giving_project" value="Next Generation Giving Project">Next Generation Giving Project<br />
                            <input type="checkbox" name="giving_project" value="Social Justice Giving Project (Portland)">Social Justice Giving Project (Portland)
                        </label>
                    </div>
                    <div class="span3">
                        <label class="input-title">Grant Status</label>
                        <label class="checkbox">
                            <input type="checkbox" name="grant_status" value="10">Received</input><br />
                            <input type="checkbox" name="grant_status" value="20">Incomplete</input><br />
                            <input type="checkbox" name="grant_status" value="30">Complete</input><br />
                            <input type="checkbox" name="grant_status" value="40">Proposal Denied</input><br />
                            <input type="checkbox" name="grant_status" value="50">Proposal Accepted</input><br />
                            <input type="checkbox" name="grant_status" value="60">Grant Denied</input><br />
                            <input type="checkbox" name="grant_status" value="70">Grant Issued</input><br />
                            <input type="checkbox" name="grant_status" value="80">Grant Paid</input><br />
                            <input type="checkbox" name="grant_status" value="90">Closed</input>
                        </label>
                    </div>
                    <div class="span3"></div>
                </div>

                <div class="row input-separator">
                    <div class="span6 offset3"></div>
                </div>

                <div class="row">
                    <div class="span3"></div>
                    <div class="span3">
                        <label class="input-title">People of Color?<br />
                            <label class="radio inline"><input type="radio" name="diverse" id="diverse_yes" value="yes">Yes</label><label class="radio inline"><input type="radio" name="diverse" id="diverse_no" value="no">No</label>
                        </label>
                    </div>
                    <div class="span3">
                        <label class="input-title">Year Start</label>
                        <input type="number" placeholder="1978" min="1978" max="2012" name="year_start">
                        <label class="input-title">Year End</label>
                        <input type="number" placeholder="1978" min="1978" max="2012" name="year_end">
                    </div>
                    <div class="span3"></div>
                </div>

                <div class="row input-separator">
                    <div class="span6 offset3"></div>
                </div>

                <div class="row">
                    <div class="span4"></div>
                    <div class="span4">
                        <button type="submit" class="btn btn-block btn-primary btn-large" value="Submit form">Submit</button>
                    </div>
                    <div class="span2"></div>
                </div>
              
                <!--<label>Location Type</label>
                <label class="radio">
                    <input type="radio" name="location_type" id="rural_radio" value="rural">
                    Rural
                </label>
                <label class="radio">
                    <input type="radio" name="location_type" id="urban_radio" value="urban">
                    Urban
                </label>-->

                <!--For future use
                <label>Issue Area</label>
                <label>Organizing Style</label>
                <label>Diversity Criteria</label>
                -->
            </form>
        </div>
    </body>
</html>

grants/templates/grants/grant_application/show.html
<!DOCTYPE html>
<!-- Python vars: grant_application, grantee -->
<html>
    <head>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/css/style.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic+SC' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
        <div class="container">
            <div class="page-header">
                <h1>{{ grant_application.organization }} // <small>{{ grant_application.city }}, {{ grant_application.state }}</small></h1>
            </div>
            <h2>Giving Project // 
                <span>
                    {% if grant_application.grant_cycle.givingproject_set.all %}
                        {% for gp in grant_application.grant_cycle.givingproject_set.all %}
                                {{ gp.title }}{% if not forloop.last %},{% endif %}
                        {% endfor %}
                    {% else %}
                        No Giving Project
                    {% endif %}
                </span>
            </h2>
            <h2>Grant Status // <span>{{ grant_application.get_screening_status_display }}</span></h2>
            <h2>People of Color // <span>{{ grant_application.scoring_bonus_poc }}</span></h2>
            <h2>Submission Date // <span>{{ grant_application.submission_time }}</span></h2>
        </div>
    </body>
</html>